version: "3.9"
services:
  python_flask:
    container_name: python_flask
    build:
        context: https://github.com/vilaj/vilaj.git
        dockerfile: docker/dockerfile_python_flask
    image: python_flask
    volumes:
      - python_flask:/app
    restart: unless-stopped
    networks:
      - bridge
  nodered_reisobot:
    container_name: nodered_reisobot
    image: nodered/node-red:latest-18
    volumes:
      - nodered_reisobot:/data
    ports:
      - "31880:1880"
    restart: unless-stopped
    networks:
      - bridge
volumes:
  nodered_reisobot:
    name: nodered_reisobot
  python_flask:
    name: python_flask
networks:
  bridge:
    driver: bridge
    name: bridge
